services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    command: sh -c 'npm run build && node dist/index.js'
    environment:
      - MONGO_URI=mongodb://mongo:27017/happmobi
      - JWT_SECRET=45543e016df4b739c7d7b084d566cf6e8af923c319a04f07c849e0663cf30f60
      - PORT=5000
    depends_on:
      - mongo
    ports:
      - '5000:5000'

  frontend:
    build: ./frontend
    ports:
      - '4200:4200'
    depends_on:
      - backend
    environment:
      - API_URL=http://localhost:5000/api

volumes:
  mongo_data:
