services:
  backend:
    build: ./backend
    command: sh -c 'npm run build && node dist/index.js'
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000
    depends_on:
      - mongo
    ports:
      - '5000:5000'
  frontend:
    build: ./frontend
    ports:
      - '4200:4200'
    depends_on:
      - backend
    environment:
      - API_URL=http://localhost:5000/api
volumes:
  mongo_data:
